name: test-supermake
run-name: Test & build ${{ github.ref_name }}
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
            go-version: '^1.21.6'
      - run: make build
