name: release-supermake
run-name: Release ${{ github.ref_name }}
on:
    push:
        tags:
            - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
            go-version: '^1.21.6'
      - run: make build
